name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:24.10
    steps:
    - uses: actions/checkout@v3
    - name: Update apt registry
      run: |
        apt update && apt install -y --no-install-recommends ca-certificates sudo && echo 'VHlwZXM6IGRlYgpVUklzOiBodHRwczovL3BwYS5sYXVuY2hwYWRjb250ZW50Lm5ldC9hcHQtZmFzdC9zdGFibGUvdWJ1bnR1LwpTdWl0ZXM6IG9yYWN1bGFyCkNvbXBvbmVudHM6IG1haW4KU2lnbmVkLUJ5OiAKIC0tLS0tQkVHSU4gUEdQIFBVQkxJQyBLRVkgQkxPQ0stLS0tLQogLgogbVFJTkJHWTBiazRCRUFEQmE4elFUeTVIaGlmQTB1dXZ0Uy81d29JNjluZ2NzNzZPQnNlamRNc3l4cEpqbmx4RQogTk5oaVltNHRqVXAycFRSM3pYVmk3VUFJNWJGY291RVRnTEk4d3piVnlrVVJ6RHc5M2I0Wk5vbG1hOW1BZjJ2KwogbE42V0FHTW1uNC9SUWc2YmQzL0dWbXZjMWYyeFQxVy83SnVCMHNvWUNwYTloOUJUbUR4ZXNoVko1YU8xWktrOAogK0VtWU90emczb28xajk4dUtLbm1pdG1DZEJOQ3U3bDJuZmlGbjhTd2dkRGhZRXR4ckZzRmxUWFEzSWRZekJNRgogejlBRkt0bnpFSVFCeVI2OHlwSEtzRWh5RzFEZDVwenA4Ni91cyt4Q1EzV3dGY2xGMWdRRExGSkFhaGZsbzNiYQogUW5BNk9sckxZMytuNmZyRE1QK2tGdWlSQ2VxU05HTEZ2R09VVWJtc0dkcW4zU0JpeEZFNkFDMVhodVVPSGk4QgogSGR1R0RDLzBjSythcTFWT3o2d3ZxYWFyc3B1SSs5THFxV0IwQVpmVVNmbndIUFZnVDVYMlQ4STVKZHVNRzA4cwogaWhxV0xMZTZVRWNMaTV5dmpJZGxvNDZmVm1FWTF2bHYzdVhUbmV6bWJpS2FwTklGdlRMRFJuSzlUMWwvSEIvWQogb1NZYi91UmVUbUdWSzM3L2x1L2tIWFdmS3grQkJnU2xPVllZZktLcVRZYzA4bk9ValdIVVdvL082Y1A0YWRregogM3ZVams4V3pBcTdEWnZHWHdrbURoUUQ2SWZ3UG9uNW00RXVZcGE4MTJZbnlUSlpaNG5sajM4OTdOOVhjNmhRUAogblNaUTVVRXZ6SGF5bTZUbnFDTXdhak55TnBmcVdSa2dMaDl1TVdaNy94cVppOTJGaENBS1lJRU10d0FSQVFBQgogdEJwTVlYVnVZMmh3WVdRZ1VGQkJJR1p2Y2lCaGNIUXRabUZ6ZElrQ1RnUVRBUW9BT0JZaEJMeFpOUDA5NjlUYQogNmxSUGVSNG9KS2Z5SzBTOUJRSm1ORzVPQWhzREJRc0pDQWNDQmhVS0NRZ0xBZ1FXQWdNQkFoNEJBaGVBQUFvSgogRUI0b0pLZnlLMFM5LzZ3UC8wNmovSXUrNCs2a3N5bkI3cDViNjh0VEo5Q1pucU93VDgxa1c3R2JQQmc5YlkyZQogLzBuaC9XK2hISWNIL2dqd3MyUnFGVW5QMzltdHVWdjBtRGFiZlFMU2pFeVVKT3cwWUpGemhpRlJYYjdZY0x1eAogRytPOTA2ZklKN0E5a0ZLTmZtRThYOTRXM0gzVTlUSjN1UmZQVHIwL2pPOWhGVzVVU0hOZDN1NU0rWEk3RGIwZQogVnE2UkJCRXMxaUZCWG5Fd2MvbSsxNDZ6dDBiM2NoM2R2dk9FaWJXREtSN3Fia25iWHpnbzV0R3M0RGdRTmM1NgogQjg2dlQ3RHpiZTA5L2Jwb3pNV3g2YTErd1F4bHcwcCt1M3dleGtjeml5MGtVcUZyWXEzRmN6NzMvMTNPWkEzRAogMFl5MHNGYkptRUxkVzNiSU9yTWJoWXZrVHZ5cmFDcm43NmlzYXF3ckFkK2JWYm5yY1NxVXRWOUFDWW9uUk95aAogb1pRVTRKQkVuaGszTnNzOHFtOHNKOTcyajFnZCtsVnU5ZXBwVDR2Zk5wNEVhWk1WRXIreUtSMjRFV1oxZ3dHRQogWVBJamJCTzY3ellBWHJUb2ZMRWVNN1lqdEFGRk9ENlVoa0N3OXNXU2VnNmlFYUpXUmJuSDhJc2ZNWU5UOE01VQogUjdCMXhjK0NlczgyTDBaSWhlSm4vU3dTOE5MWE5Fc1c4OUE3ZHRab2ZxcHNYRFlFSUF3U3lTOUtveWFwSVBFRAogR1JibE0wV2taTnZmZml2bUczK3JrcE9MSmZ6Vm9jLzJ1T2E3UTVaTGhHRjJ6VjhtL3B1WTZ1MWREOWRNTkEybwogOVBTbG1sdUdLTUxFa3I1ZzRhSFRTNEZmSElLeEVsemxmNm15RmhUSGZZYWxCRVA5RGE3YS9yZkpGd3NqCiA9WHlUMgogLS0tLS1FTkQgUEdQIFBVQkxJQyBLRVkgQkxPQ0stLS0tLQo=' | base64 -d > /etc/apt/sources.list.d/apt-fast-ubuntu-stable-oracular.sources && apt update && apt install -y --no-install-recommends apt-fast
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: uuid-dev clang-19 libcxx-19 cmake
    - name: Purge gcc
      run: sudo apt-get purge gcc
    - name: Cache Build
      id: restore-cache-build
      uses: actions/cache/restore@v4
      with:
        path: build
        key: ${{ runner.os }}-build
    - name: CMake Action
      uses: threeal/cmake-action@v2.0.0
      with:
        options: |
          CMAKE_BUILD_TYPE=Release
          ETCDF_BUILD_TESTS=true
          CMAKE_CXX_FLAGS='-D__cpp_concepts=202002L'
          CXX_FILESYSTEM_HAVE_FS=TRUE
          CMAKE_EXE_LINKER_FLAGS='-static'
        run-build: true
        c-compiler: clang-19
        cxx-compiler: clang++-19
    - uses: actions/cache/save@v3
      name: Save build cache
      with:
        path: build
        key: ${{ runner.os }}-build
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: build/bin/etcdf
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
